// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	gomail "gopkg.in/gomail.v2"

	mock "github.com/stretchr/testify/mock"
)

// GomailDialer is an autogenerated mock type for the GomailDialer type
type GomailDialer struct {
	mock.Mock
}

// DialAndSend provides a mock function with given fields: m
func (_m *GomailDialer) DialAndSend(m ...*gomail.Message) error {
	_va := make([]interface{}, len(m))
	for _i := range m {
		_va[_i] = m[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...*gomail.Message) error); ok {
		r0 = rf(m...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
